pipeline {
agent any
environment {
    JAVA_HOME="C:/Program Files/Java/jdk-21"
  }

stages {
stage('Clean stage') {
steps {
dir("my-springboot-app") {
bat 'D:/apache_maven/bin/mvn clean'
}
}
}


stage('Compile stage') {
steps {
dir("my-springboot-app") {
bat 'D:/apache_maven/bin/mvn compile'
}
}
}

stage('Install stage') {
steps {
dir("my-springboot-app") {
bat 'D:/apache_maven/bin/mvn install'
}
}
}

}
}